version: '4'
services:
  geth:
    image: ethereum/client-go:v1.13.14
    pull_policy: always
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - jwt-data:/data/FULLNODE/jwt
      - geth-data:/data/FULLNODE/geth
    command: [
      "--${GETH_NETWORK}",
      "--syncmode=snap",
      "--http",
      "--http.addr=0.0.0.0",
      "--http.vhosts=*",
      "--http.port=8545",
      "--authrpc.addr=0.0.0.0",
      "--authrpc.vhosts=*",
      "--authrpc.port=8551",
      "--discovery.port=30303",
      "--port=30303",
      "--ws",
      "--ws.addr=0.0.0.0",
      "--ws.port=8546",
      "--datadir=/data/FULLNODE/geth",
      "--pprof",
      "--pprof.addr=0.0.0.0",
      "--http.api=engine,eth,web3,net,debug",
      "--http.corsdomain=*",
      "--authrpc.jwtsecret=/data/FULLNODE/jwt/jwtsecret"
    ]
    expose:
      - "8545"
      - "8546"
      - "8551"
      - "30303"

  lighthouse:
    network_mode: "host"
    image: sigp/lighthouse:v5.2.0
    pull_policy: always
    restart: unless-stopped
    volumes:
      - jwt-data:/data/FULLNODE/jwt
      - lighthouse-data:/data/FULLNODE/lighthouse
    command: [
      "lighthouse",
      "bn",
      "--builder=${MEV_ENDPOINT}",
      "--network=${LIGHTHOUSE_NETWORK}",
      "--datadir=/data/FULLNODE/lighthouse",
      "--execution-jwt=/data/FULLNODE/jwt/jwtsecret",
      "--http",
      "--listen-address=0.0.0.0",
      "--http-address=0.0.0.0",
      "--http-port=5052",
      "--staking",
      "--http-allow-sync-stalled",
      "--execution-endpoint=http://127.0.0.1:8551",
      "--metrics",
      "--metrics-address=0.0.0.0",
      "--subscribe-all-subnets",
      "--import-all-attestations",
      "--validator-monitor-auto",
      "--checkpoint-sync-url=https://checkpoint-sync.holesky.ethpandaops.io",
    ]
    expose:
      - "5052"
      - "9000"
      - "5054"

  # Add other services similarly

volumes:
  geth-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/FULLNODE/geth
  lighthouse-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/FULLNODE/lighthouse
  jwt-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/FULLNODE/jwt
  operator-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/FULLNODE/operator
  nethermind-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/FULLNODE/nethermind
  besu-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/FULLNODE/besu
  erigon-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/FULLNODE/erigon

