version: '3.8'

services:
  geth:
    image: ethereum/client-go:v1.13.14
    pull_policy: always
    restart: unless-stopped
    network_mode: "bridge"
    volumes:
      - jwt-data:/data/FULLNODE/jwt
      - geth-data:/data/FULLNODE/geth
    command: [
      "--${GETH_NETWORK}",
      "--syncmode=snap",
      "--http",
      "--http.addr=0.0.0.0",
      "--http.vhosts=*",
      "--http.port=8545",
      "--authrpc.addr=0.0.0.0",
      "--authrpc.vhosts=*",
      "--authrpc.port=8551",
      "--discovery.port=30303",
      "--port=30303",
      "--ws",
      "--ws.addr=0.0.0.0",
      "--ws.port=8546",
      "--datadir=/data/FULLNODE/geth",
      "--pprof",
      "--pprof.addr=0.0.0.0",
      "--http.api=engine,eth,web3,net,debug",
      "--http.corsdomain=*",
      "--authrpc.jwtsecret=/data/FULLNODE/jwt/jwtsecret"
    ]
    ports:
      - "8545:8545"
      - "8546:8546"
      - "8551:8551"
      - "30303:30303"

  lighthouse:
    network_mode: "bridge"
    image: sigp/lighthouse:v5.1.2
    pull_policy: always
    restart: unless-stopped
    volumes:
      - jwt-data:/data/FULLNODE/jwt
      - lighthouse-data:/data/FULLNODE/lighthouse
    command:
      [
        "lighthouse",
        "bn",
        "--network=${LIGHTHOUSE_NETWORK}",
        "--datadir=/data/FULLNODE/lighthouse",
        "--execution-jwt=/data/FULLNODE/jwt/jwtsecret",
        "--http",
        "--listen-address=0.0.0.0",
        "--http-address=0.0.0.0",
        "--http-port=5052",
        "--staking",
        "--http-allow-sync-stalled",
        "--execution-endpoint=http://127.0.0.1:8551",
        "--metrics",
        "--metrics-address=0.0.0.0",
        "--subscribe-all-subnets",
        "--import-all-attestations",
        "--validator-monitor-auto",
        "--checkpoint-sync-url=https://checkpoint-sync.holesky.ethpandaops.io",
      ]
    ports:
      - "5052:5052"
      - "9000:9000"
      - "5054:5054"

  operator:
    network_mode: "bridge"
    volumes:
      - lighthouse-data:/data/FULLNODE/lighthouse  # Adjusted volume mapping
    image: parastate/dvf-operator:${IMAGE_TAG}
    pull_policy: always
    restart: unless-stopped
    command:
      - /bin/sh
      - -c
      - |
        dvf validator_client --metrics --debug-level=info --network=${OPERATOR_NETWORK} --beacon-nodes=${BEACON_NODE_ENDPOINT} --api=${API_SERVER} --ws-url=${WS_URL}  --ip=${NODE_IP} --id=${OPERATOR_ID} --registry-contract=${REGISTRY_CONTRACT_ADDRESS} --network-contract=${NETWORK_CONTRACT_ADDRESS} --base-port=26000 2>&1
    ports:
      - "26000:26000"
      - "26001:26001"
      - "26002:26002"
      - "26003:26003"
      - "26004:26004"
      - "26005:26005"
      - "5064:5064"
    deploy:
      resources:
        limits:
          memory: 5G

  dvf_key_tool:
    network_mode: "bridge"
    volumes:
      - lighthouse-data:/data/FULLNODE/lighthouse  # Adjusted volume mapping
    image: parastate/dvf-operator:${IMAGE_TAG}
    pull_policy: always
    command:
      - /bin/sh
      - -c
      - |
        dvf_key_tool ${OPERATOR_NETWORK}
    deploy:
      resources:
        limits:
          memory: 5G

  nethermind:
    image: nethermind/nethermind
    pull_policy: always
    restart: unless-stopped
    network_mode: "bridge"
    volumes:
      - jwt-data:/data/FULLNODE/jwt
      - nethermind-data:/data/FULLNODE/nethermind
    command: [
      "--config=${NETHERMIND_NETWORK}",
      "--JsonRpc.Enabled=true",
      "--JsonRpc.EngineHost=0.0.0.0",
      "--JsonRpc.EnginePort=8551",
      "--JsonRpc.WebSocketsPort=8546",
      "--JsonRpc.Host=0.0.0.0",
      "--JsonRpc.JwtSecretFile=/data/FULLNODE/jwt/jwtsecret",
      "--datadir=/data/FULLNODE/nethermind",
    ]
    ports:
      - "8551:8551"
      - "8546:8546"
      - "30303:30303"

  besu:
    image: hyperledger/besu
    pull_policy: always
    restart: unless-stopped
    network_mode: "bridge"
    user: "0"
    volumes:
      - jwt-data:/data/FULLNODE/jwt
      - besu-data:/data/FULLNODE/besu
    command: [
      "--network=${BESU_NETWORK}",
      "--rpc-http-enabled=true",
      "--engine-rpc-port=8551",
      "--rpc-ws-enabled",
      "--rpc-ws-host=0.0.0.0",
      "--rpc-ws-port=8546",
      "--host-allowlist=*",
      "--engine-host-allowlist=*",
      "--engine-jwt-secret=/data/FULLNODE/jwt/jwtsecret",
      "--data-storage-format=BONSAI",
      "--data-path=/data/FULLNODE/besu",
    ]
    ports:
      - "8551:8551"
      - "8546:8546"
      - "30303:30303"

  erigon:
    image: thorax/erigon:v2.59.0
    pull_policy: always
    restart: unless-stopped
    network_mode: "bridge"
    user: "0"
    volumes:
      - jwt-data:/data/FULLNODE/jwt
      - erigon-data:/data/FULLNODE/erigon
    command: [
      "--chain=${ERIGON_NETWORK}",
      "--authrpc.port=8551",
      "--ws",
      "--authrpc.jwtsecret=/data/FULLNODE/jwt/jwtsecret",
      "--datadir=/data/FULLNODE/erigon",
      "--prune=htc",
      "--prune.r.before=4367322"
    ]
    ports:
      - "8551:8551"
      - "8545:8545"
      - "30303:30303"

volumes:
  geth-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/FULLNODE/geth
  lighthouse-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/FULLNODE/lighthouse
  jwt-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/FULLNODE/jwt
  operator-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/FULLNODE/operator
  nethermind-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/FULLNODE/nethermind
  besu-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/FULLNODE/besu
  erigon-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/FULLNODE/erigon

networks:
  dvf_network:
    driver: bridge
